version: "3.9"

networks:
  dev-network:
    driver: bridge

services:
  db:
    image: postgres:latest
    container_name: db
    env_file:
      - ./FunPart/.env
    ports:
      - "5432:5432"
    volumes:
      - ./FunPart/migrations/00001_init.up.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    networks:
      - dev-network

  backend:
    container_name: backend
    build:
      context: ./FunPart
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "7236:7236"
    restart: always
    networks:
      - dev-network
    depends_on:
      - db